### ISSUE TITLE
Fix this problem

### ISSUE THREAD

**Issue by ItsaPerryBob** [LunizStudios/ikt-schoolprojects#1]
fuck it!

**Comment by ItsaPerryBob** [comment]
@jekkenmann  fuck you upload bloody damn it

**Comment by ItsaPerryBob** [comment]
[Oppgave Fronter.docx](https://github.com/LunizStudios/ikt-schoolprojects/files/456157/Oppgave.Fronter.docx)

**Comment by jekkenmann** [comment]
hei

**Comment by jekkenmann** [comment]
fuck deg?
